export const SLOTS_DATA = [
  { name: "Gates of Olympus", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "⚡", theme: "Mythology" },
  { name: "Sweet Bonanza", provider: "Pragmatic Play", volatility: "High", max_win: 21175, rtp: 96.51, emoji: "🍭", theme: "Candy" },
  { name: "Dog House Megaways", provider: "Pragmatic Play", volatility: "High", max_win: 10000, rtp: 96.55, emoji: "🐶", theme: "Animals" },
  { name: "Starlight Princess", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "⭐", theme: "Fantasy" },
  { name: "Big Bass Bonanza", provider: "Pragmatic Play", volatility: "Medium", max_win: 2100, rtp: 96.71, emoji: "🎣", theme: "Fishing" },
  { name: "Big Bass Splash", provider: "Pragmatic Play", volatility: "Medium", max_win: 2000, rtp: 96.71, emoji: "🐟", theme: "Fishing" },
  { name: "Big Bass Amazon Xtreme", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.06, emoji: "🌿", theme: "Fishing" },
  { name: "Fruit Party", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "🍇", theme: "Fruit" },
  { name: "Fruit Party 2", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.49, emoji: "🍓", theme: "Fruit" },
  { name: "Wild West Gold", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.51, emoji: "🤠", theme: "Western" },
  { name: "John Hunter and the Book of Tut", provider: "Pragmatic Play", volatility: "High", max_win: 2500, rtp: 96.50, emoji: "🏺", theme: "Egypt" },
  { name: "5 Lions Gold", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.49, emoji: "🦁", theme: "Asian" },
  { name: "Fire Strike", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.52, emoji: "🔥", theme: "Classic" },
  { name: "Chilli Heat Megaways", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "🌶️", theme: "Mexican" },
  { name: "Gems Bonanza", provider: "Pragmatic Play", volatility: "High", max_win: 10000, rtp: 96.51, emoji: "💎", theme: "Gems" },
  { name: "Aztec Bonanza", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "🏛️", theme: "Aztec" },
  { name: "Power of Thor Megaways", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.49, emoji: "⚡", theme: "Mythology" },
  { name: "Buffalo King Megaways", provider: "Pragmatic Play", volatility: "Very High", max_win: 10000, rtp: 96.52, emoji: "🦬", theme: "Animals" },
  { name: "Curse of the Werewolf Megaways", provider: "Pragmatic Play", volatility: "Very High", max_win: 8232, rtp: 96.50, emoji: "🐺", theme: "Horror" },
  { name: "The Dog House", provider: "Pragmatic Play", volatility: "High", max_win: 6750, rtp: 96.51, emoji: "🏠", theme: "Animals" },
  { name: "Release the Kraken", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.51, emoji: "🐙", theme: "Sea" },
  { name: "Magician's Secrets", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "🎩", theme: "Magic" },
  { name: "Sugar Rush", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "🍬", theme: "Candy" },
  { name: "Sugar Rush 1000", provider: "Pragmatic Play", volatility: "Very High", max_win: 5000, rtp: 96.52, emoji: "🍰", theme: "Candy" },
  { name: "Wolf Gold", provider: "Pragmatic Play", volatility: "Medium", max_win: 1000, rtp: 96.01, emoji: "🐺", theme: "Animals" },
  { name: "Cash Elevator", provider: "Pragmatic Play", volatility: "Very High", max_win: 10000, rtp: 96.49, emoji: "🏢", theme: "Classic" },
  { name: "Zeus vs Hades Gods of War", provider: "Pragmatic Play", volatility: "Very High", max_win: 5000, rtp: 96.50, emoji: "⚡", theme: "Mythology" },
  { name: "Big Juan", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.49, emoji: "🌮", theme: "Mexican" },
  { name: "Asgard Saga", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.51, emoji: "🛡️", theme: "Viking" },
  { name: "Gold Train", provider: "Pragmatic Play", volatility: "High", max_win: 5000, rtp: 96.49, emoji: "🚂", theme: "Western" },
  { name: "Book of Dead", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.21, emoji: "📖", theme: "Egypt" },
  { name: "Reactoonz", provider: "Play'n GO", volatility: "Very High", max_win: 4570, rtp: 96.51, emoji: "👾", theme: "Aliens" },
  { name: "Legacy of Dead", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.58, emoji: "🏺", theme: "Egypt" },
  { name: "Rise of Olympus", provider: "Play'n GO", volatility: "Very High", max_win: 5000, rtp: 96.50, emoji: "🏛️", theme: "Mythology" },
  { name: "Tome of Madness", provider: "Play'n GO", volatility: "High", max_win: 2000, rtp: 96.35, emoji: "📕", theme: "Horror" },
  { name: "Sword of Ares", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.36, emoji: "⚔️", theme: "Mythology" },
  { name: "Moon Princess", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.50, emoji: "🌙", theme: "Fantasy" },
  { name: "Cat Wilde and the Doom of Dead", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.32, emoji: "🐱", theme: "Egypt" },
  { name: "Fire Joker", provider: "Play'n GO", volatility: "High", max_win: 800, rtp: 96.15, emoji: "🃏", theme: "Classic" },
  { name: "Reactoonz 2", provider: "Play'n GO", volatility: "Very High", max_win: 4570, rtp: 96.20, emoji: "👽", theme: "Aliens" },
  { name: "Troll Hunters 2", provider: "Play'n GO", volatility: "Very High", max_win: 5000, rtp: 96.21, emoji: "🧌", theme: "Fantasy" },
  { name: "Solar Queen", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.23, emoji: "☀️", theme: "Egypt" },
  { name: "Ganesha Fortune", provider: "Play'n GO", volatility: "High", max_win: 5000, rtp: 96.20, emoji: "🐘", theme: "Asian" },
  { name: "Razor Shark", provider: "Push Gaming", volatility: "High", max_win: 50000, rtp: 96.70, emoji: "🦈", theme: "Sea" },
  { name: "Jammin Jars 2", provider: "Push Gaming", volatility: "Very High", max_win: 20000, rtp: 96.50, emoji: "🫙", theme: "Fruit" },
  { name: "Jammin Jars", provider: "Push Gaming", volatility: "Very High", max_win: 20000, rtp: 96.83, emoji: "🍒", theme: "Fruit" },
  { name: "Fat Banker", provider: "Push Gaming", volatility: "Very High", max_win: 100000, rtp: 96.56, emoji: "🏦", theme: "Comedy" },
  { name: "Fat Santa", provider: "Push Gaming", volatility: "Medium", max_win: 10000, rtp: 96.60, emoji: "🎅", theme: "Christmas" },
  { name: "Wild Swarm", provider: "Push Gaming", volatility: "High", max_win: 10000, rtp: 96.83, emoji: "🐝", theme: "Nature" },
  { name: "Midnight Marauder", provider: "Push Gaming", volatility: "Very High", max_win: 50000, rtp: 96.50, emoji: "🌙", theme: "Crime" },
  { name: "Dinopolis", provider: "Push Gaming", volatility: "High", max_win: 20000, rtp: 96.50, emoji: "🦕", theme: "Dinosaurs" },
  { name: "Squealin Riches", provider: "Push Gaming", volatility: "Very High", max_win: 20000, rtp: 96.52, emoji: "🐷", theme: "Animals" },
  { name: "Dead or Alive 2", provider: "NetEnt", volatility: "Very High", max_win: 100000, rtp: 96.82, emoji: "🤠", theme: "Western" },
  { name: "Starburst", provider: "NetEnt", volatility: "Low", max_win: 500, rtp: 96.09, emoji: "💫", theme: "Classic" },
  { name: "Gonzo's Quest", provider: "NetEnt", volatility: "Medium", max_win: 2500, rtp: 95.97, emoji: "🗿", theme: "Adventure" },
  { name: "Gonzo's Quest Megaways", provider: "NetEnt", volatility: "High", max_win: 21000, rtp: 96.00, emoji: "🏔️", theme: "Adventure" },
  { name: "Blood Suckers", provider: "NetEnt", volatility: "Low", max_win: 298, rtp: 98.00, emoji: "🧛", theme: "Horror" },
  { name: "Blood Suckers 2", provider: "NetEnt", volatility: "Medium", max_win: 1000, rtp: 96.94, emoji: "🦇", theme: "Horror" },
  { name: "Immortal Romance", provider: "NetEnt", volatility: "Medium", max_win: 3645, rtp: 96.86, emoji: "❤️", theme: "Horror" },
  { name: "Piggy Riches Megaways", provider: "NetEnt", volatility: "High", max_win: 7500, rtp: 96.62, emoji: "🐷", theme: "Comedy" },
  { name: "Hall of Gods", provider: "NetEnt", volatility: "High", max_win: 10000, rtp: 95.70, emoji: "⚡", theme: "Mythology" },
  { name: "Wanted Dead or Wild", provider: "Hacksaw Gaming", volatility: "Very High", max_win: 12500, rtp: 96.38, emoji: "🔫", theme: "Western" },
  { name: "Chaos Crew", provider: "Hacksaw Gaming", volatility: "Very High", max_win: 7776, rtp: 96.00, emoji: "💀", theme: "Crime" },
  { name: "Chaos Crew 2", provider: "Hacksaw Gaming", volatility: "Very High", max_win: 10000, rtp: 96.10, emoji: "👊", theme: "Crime" },
  { name: "Stick Em", provider: "Hacksaw Gaming", volatility: "Very High", max_win: 25000, rtp: 96.10, emoji: "🎯", theme: "Classic" },
  { name: "Cash Compass", provider: "Hacksaw Gaming", volatility: "High", max_win: 5000, rtp: 96.51, emoji: "🧭", theme: "Adventure" },
  { name: "Cluster Tumble", provider: "Hacksaw Gaming", volatility: "Very High", max_win: 20000, rtp: 96.10, emoji: "🧱", theme: "Abstract" },
  { name: "Esqueleto Explosivo 2", provider: "Thunderkick", volatility: "High", max_win: 5040, rtp: 96.38, emoji: "💀", theme: "Mexican" },
  { name: "Midas Golden Touch", provider: "Thunderkick", volatility: "High", max_win: 8100, rtp: 96.08, emoji: "👑", theme: "Mythology" },
  { name: "Flame Busters", provider: "Thunderkick", volatility: "High", max_win: 1829, rtp: 96.06, emoji: "🔥", theme: "Retro" },
  { name: "1429 Uncharted Seas", provider: "Thunderkick", volatility: "Medium", max_win: 670, rtp: 98.60, emoji: "🌊", theme: "Sea" },
  { name: "Pink Elephants 2", provider: "Thunderkick", volatility: "Very High", max_win: 5000, rtp: 96.10, emoji: "🐘", theme: "Fantasy" },
  { name: "Beat the Beast Kraken's Lair", provider: "Thunderkick", volatility: "High", max_win: 2222, rtp: 96.11, emoji: "🐙", theme: "Sea" },
  { name: "Fire in the Hole", provider: "Nolimit City", volatility: "Very High", max_win: 60000, rtp: 96.00, emoji: "💣", theme: "Western" },
  { name: "Mental", provider: "Nolimit City", volatility: "Very High", max_win: 50000, rtp: 96.00, emoji: "🧠", theme: "Horror" },
  { name: "Tombstone No Mercy", provider: "Nolimit City", volatility: "Very High", max_win: 100000, rtp: 96.08, emoji: "⚰️", theme: "Western" },
  { name: "San Quentin xWays", provider: "Nolimit City", volatility: "Very High", max_win: 150000, rtp: 96.05, emoji: "🔒", theme: "Crime" },
  { name: "Punk Rocker", provider: "Nolimit City", volatility: "Very High", max_win: 45000, rtp: 96.03, emoji: "🤘", theme: "Rock" },
  { name: "Deadwood", provider: "Nolimit City", volatility: "Very High", max_win: 138240, rtp: 96.11, emoji: "🏚️", theme: "Western" },
  { name: "Tombstone RIP", provider: "Nolimit City", volatility: "Very High", max_win: 66666, rtp: 96.12, emoji: "💀", theme: "Western" },
  { name: "East Coast vs West Coast", provider: "Nolimit City", volatility: "Very High", max_win: 30000, rtp: 96.05, emoji: "🎤", theme: "Hip-Hop" },
  { name: "Infectious 5 xWays", provider: "Nolimit City", volatility: "Very High", max_win: 50000, rtp: 96.06, emoji: "🦠", theme: "Horror" },
  { name: "Road Rage", provider: "Nolimit City", volatility: "Very High", max_win: 65000, rtp: 96.00, emoji: "🏍️", theme: "Biker" },
  { name: "Warrior Graveyard xNudge", provider: "Nolimit City", volatility: "Very High", max_win: 34560, rtp: 96.06, emoji: "⚔️", theme: "Fantasy" },
  { name: "Ice Ice Yeti", provider: "Nolimit City", volatility: "Very High", max_win: 32768, rtp: 96.00, emoji: "🧊", theme: "Adventure" },
  { name: "Rock Bottom", provider: "Nolimit City", volatility: "Very High", max_win: 50000, rtp: 96.07, emoji: "🎸", theme: "Rock" },
  { name: "Bonanza Megaways", provider: "Big Time Gaming", volatility: "High", max_win: 10000, rtp: 96.00, emoji: "💰", theme: "Mining" },
  { name: "Extra Chilli", provider: "Big Time Gaming", volatility: "Very High", max_win: 20000, rtp: 96.00, emoji: "🌶️", theme: "Mexican" },
  { name: "White Rabbit Megaways", provider: "Big Time Gaming", volatility: "Very High", max_win: 15000, rtp: 97.72, emoji: "🐰", theme: "Fairy Tale" },
  { name: "Danger High Voltage", provider: "Big Time Gaming", volatility: "Very High", max_win: 10000, rtp: 95.67, emoji: "⚡", theme: "Music" },
  { name: "Star Clusters Megaclusters", provider: "Big Time Gaming", volatility: "High", max_win: 10000, rtp: 96.00, emoji: "🌟", theme: "Space" },
  { name: "Nitropolis 4", provider: "ELK Studios", volatility: "Very High", max_win: 50000, rtp: 96.00, emoji: "🐾", theme: "Cyberpunk" },
  { name: "Nitropolis 3", provider: "ELK Studios", volatility: "Very High", max_win: 50000, rtp: 96.00, emoji: "🐺", theme: "Cyberpunk" },
  { name: "Wild Toro 2", provider: "ELK Studios", volatility: "Very High", max_win: 25000, rtp: 96.00, emoji: "🐂", theme: "Animals" },
  { name: "Valholl Megaways", provider: "ELK Studios", volatility: "Very High", max_win: 10000, rtp: 96.10, emoji: "🛡️", theme: "Viking" },
  { name: "Gold Digger Megaways", provider: "ELK Studios", volatility: "Very High", max_win: 50000, rtp: 96.00, emoji: "⛏️", theme: "Mining" },
  { name: "Cygnus", provider: "ELK Studios", volatility: "High", max_win: 5000, rtp: 96.00, emoji: "🦢", theme: "Space" },
  { name: "Money Train 4", provider: "Relax Gaming", volatility: "Very High", max_win: 100000, rtp: 96.15, emoji: "🚂", theme: "Western" },
  { name: "Money Train 3", provider: "Relax Gaming", volatility: "Very High", max_win: 100000, rtp: 96.10, emoji: "🚃", theme: "Western" },
  { name: "Money Train 2", provider: "Relax Gaming", volatility: "Very High", max_win: 50000, rtp: 96.40, emoji: "🚄", theme: "Western" },
  { name: "Hellcatraz", provider: "Relax Gaming", volatility: "Very High", max_win: 261632, rtp: 96.30, emoji: "🔒", theme: "Crime" },
  { name: "Temple Tumble 2", provider: "Relax Gaming", volatility: "Very High", max_win: 50000, rtp: 96.14, emoji: "🏛️", theme: "Aztec" },
  { name: "Volatile Slot", provider: "Relax Gaming", volatility: "Very High", max_win: 50000, rtp: 96.19, emoji: "💥", theme: "Abstract" },
  { name: "Vikings Go Berzerk", provider: "Yggdrasil", volatility: "Very High", max_win: 10000, rtp: 96.10, emoji: "⛵", theme: "Viking" },
  { name: "Wolf Hunters", provider: "Yggdrasil", volatility: "Very High", max_win: 10000, rtp: 96.00, emoji: "🐺", theme: "Horror" },
  { name: "Lilith's Inferno", provider: "Yggdrasil", volatility: "Very High", max_win: 8000, rtp: 96.20, emoji: "😈", theme: "Horror" },
  { name: "Hades Gigablox", provider: "Yggdrasil", volatility: "High", max_win: 5000, rtp: 96.10, emoji: "💀", theme: "Mythology" },
  { name: "9 Coins", provider: "Wazdan", volatility: "High", max_win: 5000, rtp: 96.20, emoji: "🪙", theme: "Classic" },
  { name: "Black Horse Deluxe", provider: "Wazdan", volatility: "Very High", max_win: 500000, rtp: 96.31, emoji: "🐴", theme: "Animals" },
  { name: "Book of Vlad", provider: "Spinomenal", volatility: "High", max_win: 10000, rtp: 96.08, emoji: "🧛", theme: "Horror" },
  { name: "Book of the Fallen", provider: "Spinomenal", volatility: "High", max_win: 5000, rtp: 95.98, emoji: "📗", theme: "Fantasy" },
]

export const PROVIDERS = [...new Set(SLOTS_DATA.map(s => s.provider))].sort()
export const VOLATILITIES = ["Low", "Medium", "High", "Very High"]
export const THEMES = [...new Set(SLOTS_DATA.map(s => s.theme))].sort()
